# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 587cac29072d09ef28b7cf365b29ca46cc480da7f7eb1e0487c2d463d4f5b13a20f10d96dfca768744e9868265ea58d9d74809d8a08e8d2ed8db9e3bd288f74a

test:
  secret_key_base: a50e9016808587b6b3527a16551a4d8e88bf7d14627b8be68d6cdd5ae6a48de796f4098d992fd1d18e715c1190502e49434712983343c130228de5c15a0a4a74

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
